name: Build-Savage-Blue-2026
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: brew install ldid dpkg

      - name: Install Theos & SDK
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          mkdir -p $THEOS/sdks
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS/sdks-tmp
          mv $THEOS/sdks-tmp/iPhoneOS14.5.sdk $THEOS/sdks/
          rm -rf $THEOS/sdks-tmp

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1 SDKVERSION=14.5

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Savage-Blue-Final
          path: packages/*.deb
